/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author adaltoss
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPainel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuItemClientesCadastrar = new javax.swing.JMenuItem();
        menuItemClientesListar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemProdutosGerenciar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Inicial");
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jMenu1.setText("Arquivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clientes");

        menuItemClientesCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuItemClientesCadastrar.setText("Cadastrar");
        menuItemClientesCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClientesCadastrarActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemClientesCadastrar);

        menuItemClientesListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        menuItemClientesListar.setText("Listar");
        jMenu2.add(menuItemClientesListar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Produtos");

        menuItemProdutosGerenciar.setText("Gerenciar...");
        menuItemProdutosGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProdutosGerenciarActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemProdutosGerenciar);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPainel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemClientesCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClientesCadastrarActionPerformed
        
        FormCliente tela = new FormCliente();
        jdpPainel.add( tela );
        tela.setVisible( true );
        
    }//GEN-LAST:event_menuItemClientesCadastrarActionPerformed

    private void menuItemProdutosGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProdutosGerenciarActionPerformed
        FormProdutos tela = new FormProdutos();
        jdpPainel.add( tela );
        tela.setVisible( true );
    }//GEN-LAST:event_menuItemProdutosGerenciarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpPainel;
    private javax.swing.JMenuItem menuItemClientesCadastrar;
    private javax.swing.JMenuItem menuItemClientesListar;
    private javax.swing.JMenuItem menuItemProdutosGerenciar;
    // End of variables declaration//GEN-END:variables
}
